[versions]
agp = "8.5.1"
androidxJunit = "1.1.5"
appcompatVersion = "1.6.1"
circleimageview = "3.1.0"
constraintlayoutVersion = "2.1.4"
espressoCoreVersion = "3.5.1"
firebaseBom = "34.6.0"
firebaseBomVersion = "32.8.1"
googleMaterial = "1.11.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.0"
constraintlayout = "2.2.1"
materialVersion = "1.12.0"
osmdroidAndroid = "6.1.20"
playServicesLocation = "21.3.0"
recyclerview = "1.4.0"
viewpager2 = "1.1.0"
firebaseAuth = "24.0.1"
preference = "1.2.1"

[libraries]
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
com-google-firebase-firebase-auth = { module = "com.google.firebase:firebase-auth" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-bom-v3281 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
google-firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

